### ISSUE TITLE
Live channels not working, missing episode thumbnails

### ISSUE THREAD

**Issue by codydude1** [benaranguren/nuodtayo.tv#1]
Hi benaranguren, I was wondering if you are working on a fix to restore the live channels that was working on cmik's v.58. Also individual tv episodes don't have thumbnails, I can't preview them atm.

**Comment by benaranguren** [comment]
Thank you for reminding me this issue.  Yes, it will get fixed.

**Comment by benaranguren** [comment]
@codydude1 this will hopefully now work in v0.1.7 f7acb8118ce07d90adc2953671853f93cb1ee53b

**Comment by codydude1** [comment]
Thanks a lot. The addon is now perfect.
