### ISSUE TITLE
TFC wont play anything as of 06-24-18

### ISSUE THREAD

**Issue by HenioH** [benaranguren/nuodtayo.tv#16]
This addon and the CMik one have both stop playing videos as of yesterday. On other forums people are posting the error that I myself is getting. Account is valid but says it has expired. Accounts work well on website but not in the two addons anymore. Please help.

**Comment by nuodtayo** [comment]
Somehow I missed your message.  Anyway, there's an update for this add-on, v0.1.19.  cmik has also released an update.
