### ISSUE TITLE
Settings - view number of episodes

### ISSUE THREAD

**Issue by islandtj** [benaranguren/nuodtayo.tv#3]
Aloha Benaranguren, under "shows", subtitled section, when we try to advance episodes to get to the earlier episodes, the app will only advance 8 episodes per screen - regardless of the settings parameter (10,20,30,40 or 50). Would you be able to resolve?

I appreciate your efforts thus far :)

**Comment by benaranguren** [comment]
Aloha @islandtj, I just tried it with v0.1.7 and it seems to work for me.  Can you confirm the version you are using?

**Comment by rockers961** [comment]
I just tried it and it was working just fine with me. I am on v0.1.7

**Comment by benaranguren** [comment]
Thanks, I see the issue now. It's not the number of items displayed it's where the next page starts.

**Comment by islandtj** [comment]
Correct, it's where the next page starts.  While the app does list the episode amount specified in the settings section, when you advance to the next page it will list the correct number of episodes but will only advance 8 at a time.  For shows with 100+ episodes, it takes a while to forward to episode #1.

Mahalo again benaranguren!

**Comment by benaranguren** [comment]
This should be fixed in v0.1.8.  @islandtj, can you please give it a try?

**Comment by islandtj** [comment]
Wow, it is fixed! A big mahalo and blessings to you benaranguren! My wife and I really appreciate your efforts.
