### ISSUE TITLE
Pixelation issue

### ISSUE THREAD

**Issue by rockers961** [benaranguren/nuodtayo.tv#5]
TFC.tv having pixelation issues this morning...

**Comment by whoopderitis** [comment]
Same here. Videos look really blurry. I'm hard wired to my modem, so speed isn't the issue. I have 50/50MB speeds.

**Comment by fonexpert8** [comment]
Also here in New York City

**Comment by benaranguren** [comment]
The m3u8 playlist contains links for the all the bitrates but it looks like it's selecting the lowest quality for some reason.  I tried removing the lower bitrates hoping it would be forced to use only HD but unfortunately, I just get HTTP error 403/Forbidden.  It's still possible this is an issue on the server side.

**Comment by bolinao** [comment]
The quality of live tv is not pixelated.

**Comment by kulog99** [comment]
I tried cmik latest version 0.60 with the same poor quality video also but it's clear when using TFC.tv app in Android.

**Comment by cmik** [comment]
@benaranguren 
Try this fix by @gwapoman https://github.com/cmik/cmik.xbmc/blob/master/plugin.video.tfctv/default.py#L285

**Comment by islandtj** [comment]
You guys (benaranguren & cmik) are awesome!  Mahalo for your efforts and fixes!

**Comment by sydwin20** [comment]
you guys rock! i appreciate all the Time and hard work..

**Comment by ricardobothe** [comment]
Great work, @gwapoman.  And again..Thank you guys @benaranguren and @cmik for your great efforts.   Big thumbs up..

**Comment by rockers961** [comment]
Thanks for all hardwork guys.

**Comment by benaranguren** [comment]
Merged fix from @gwapoman in v0.1.10

**Comment by sydwin20** [comment]
Thanks Again!
